# como se obtiene un producto al hacer la peticion de tipo get
components:
  schemas:
    Product:
      type: object
      required:
        - _id
        - nombre
        - descripcion
        - url
        - precio
        - stock
      properties:
        _id:
          type: string
          description: "Id generado automaticamente desde la base de datos"
        nombre:
          type: string
          description: "Nombre del producto"
        descripcion:
          type: string
          description: "Descripcion del producto"
        url:
          type: string
          description: "Url de la imagen del producto"
        precio:
          type: number
          descripcion: "Precio del producto"
        stock:
          type: number
          descripcion: "Stock disponible del producto"
      example:
        _id: 640fdd793a92d7dc292ca2fa
        nombre: Gorra Pikachu
        descripcion: Una gorra del pokemon mas popular
        url: https://d3ugyf2ht6aenh.cloudfront.net/stores/405/662/products/gorra-pikachu-blanca-y-negra1-f46fef758ddc9dc90616166933804303-480-0.webp
        precio: 1234
        stock: 24